package:
    name: rvic
    version: "1.1.0"

source:
    git_url: https://github.com/UW-Hydro/RVIC.git
    git_rev: rvic.1.1.0

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - netcdf4
        - numpy
        - scipy
        - pandas
        - matplotlib

test:
    imports:
        - rvic

about:
    home: http://rvic.readthedocs.org
    license: GPLv3
    summary: 'RVIC streamflow routing model'
